### ISSUE TITLE
Add Remote Syntax for Chunk

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-flow#106]
We should add remote syntax for `Chunk`. As part of this we should think about the best way to support collection types since there is a risk of a combinatorial explosion in collection variants. Potentially everything that doesn't return the same collection type can be defined as an extension method on `Iterable`. Perhaps we can have our own version of `BuildFrom` that is serializable for the rest.

**Comment by jdegoes** [comment]
I think the server will only have a single collection type (or maybe two, if there are sets, as well). But "front-ends" can have all collection types that are deemed useful and syntax for working with them.
