### ISSUE TITLE
Implement Key Value Store Backed by Cassandra

### ISSUE THREAD

**Issue by adamgfraser** [zio/zio-flow#123]
We should have an implementation of the `KeyValueStore` backed by Cassandra. This should be defined in a separate module.

**Comment by ithinkicancode** [comment]
@ashprakasan @adamgfraser I'm taking a stab at this ticket.

The current interface of `KeyValueStore` is:
```scala
trait KeyValueStore {
  def put(namespace: String, key: Chunk[Byte], value: Chunk[Byte]): IO[IOException, Boolean]
  def get(namespace: String, key: Chunk[Byte]): IO[IOException, Option[Chunk[Byte]]]
  def scanAll(namespace: String): ZStream[Any, IOException, (Chunk[Byte], Chunk[Byte])]
}
```
(I understand, per #122, there will be one (or more) new method(s) to be added for Column Family creation.)

The `get` and `put` methods don't seem to have enough parameters to build the CQL statements for C*. The missing info is names of the key column and the value column. Are we going to have fixed names for the two columns (maybe via some configuration)?

**Comment by adamgfraser** [comment]
@ithinkicancode I don't think we need to add any more methods to `KeyValueStore`. The contract will be that if you `put` a value into a `namespace` that doesn't already exist the implementation should create the appropriate `namespace` and then `put` the value.

Yes, I think we can just use fixed names. Right now I would just pick some names that make sense (e.g. `_zflow_key_value_store_key`) and not worry about configurability.

**Comment by ithinkicancode** [comment]
Got it. Thanks Adam.
