### ISSUE TITLE
Create realistic mockup of workflow

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-flow#13]
We should create a full-fledged mockup of a workflow that demonstrates `StateVar`, `Activity`, and of course, `Workflow`.

Could be inspired by one of the following use cases:

 - [Cadence Use Cases](https://cadenceworkflow.io/docs/use-cases/)
 - [Temporal.io Use Cases](https://docs.temporal.io/docs/use-cases-orchestration)
 - [Zenaton Use Cases](https://zenaton.com/workflows-examples)

**Comment by mohnishkodnani** [comment]
One thing that I have found missing from a lot of frameworks is how to model a classic request/response pattern using a workflow model. 
The classic requirement would be an HTTP or a grpc request comes in and that instantiates a workflow. The tasks or activities within the workflow should be able to modify the incoming request to them before passing them along to downstream activity or task that might have a dependency and the same for then outgoing response to upstream tasks and eventually send the response back to the caller of the HTTP/grpc endpoint.

This might be useful when a business wants to decentralize parts of the their current business logic into pieces owned by different teams within the organization and be able to allow plug n play of tasks by different teams to test various versions of the workflow using different tasks.

**Comment by jdegoes** [comment]
@mohnishkodnani I think the design we're exploring will be capable of that. I'll make a note to check!
