### ISSUE TITLE
Ensure that all flows and remotes are completely serializable

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-flow#139]
The scheme we decided upon:

1. Any time a user-defined data type enters the API, the user-defined data type will be converted to a `DynamicValue` with the aid of a user-provided implicit `Schema` for their own custom data type.
2. Any time a user-defined data type is returned from the API (ultimately by the ZIO Flow Server), the user-defined data type will be _reconstructed_ from a `DynamicValue` with the aid of a user-provided implicit `Schema` for this custom data type.

Thus, `Schema` will appear at the edge of the API (on input and output), but no where on the server side, which will compute in terms of `DynamicValue` only.

**Comment by vigoo** [comment]
Done in #138
