### ISSUE TITLE
Serialization that works with Json codec does not work with protobuf

### ISSUE THREAD

**Issue by vigoo** [zio/zio-flow#144]
**ISSUE**

This is in fact (very likely) a zio-schema issue, but it is reproducible with zio-flow tests. 
Serialization of _remote values_ in zio-flow is implemented using zio-schema. The library defines the schema of all the remote types we have, and the actual serialization is the responsibility of a zio-schema _codec_. This allows us to switch between different serialization formats without implementing codecs for them one by one.

There is a test suite that performs roundtrip serialization tests for all the supported zio-flow remote types: serializing with a given codec, then reading back and comparing the result with the original value. 

The issue is that this test passes with the **JSON** codec, but fails with **protobuf**.

**SOLUTION**

Solving this issue requires debugging the protobuf implementation in zio-schema, comparing it with the JSON codec. Ideally the fix would be in zio-schema with a test reproducing the issue there. If that works you can also enable the roundtrip serialization tests in zio-flow for the protobuf codec.

**IMPACT**

Fixing this problem is potentially a fix for all libraries that want to serialize with zio-schema using the protobuf codec.

**WHERE TO LOOK**

- To reproduce the issue, uncomment this line: https://github.com/zio/zio-flow/blob/main/zio-flow/shared/src/test/scala/zio/flow/serialization/RemoteSerializationSpec.scala#L18
- The actual problem is most likely in this implementation: https://github.com/zio/zio-schema/blob/main/zio-schema-protobuf/shared/src/main/scala/zio/schema/codec/ProtobufCodec.scala

**Comment by petoalbert** [comment]
I can check this.
