### ISSUE TITLE
Create tests for zio-flow-rocksdb

### ISSUE THREAD

**Issue by vigoo** [zio/zio-flow#164]
**ISSUE**

`zio-flow` supports different databases to persists its executor state. Currently we have a `KeyValueStore` interface and implementations for them for Cassandra, DynamoDB and RocksDB, each of them in a separate sub project.

While Cassandra and DynamoDB also have integration tests, RocksDB does not have any yet. We should cover that implementation with integration tests similar to the other two.

**SOLUTION**

Add an integration test to the `zio-flow-rocksdb` sub project that tests all the current functionalities of the key value store interface.

**IMPACT**

The persistence layer of zio-flow is not final yet, for example the ongoing work on supporting transactions changes a little bit the key-value store interface, and also we will need to implement an `IndexedStore` which will require its own tests. Having tests for the existing RocksDB implementation and a place to put new tests for will help a lot in making these changes.

**WHERE TO LOOK**

 - See the `cassandra` and `dynamodb` sub projects in `zio-flow` that already have tests
 - Check how `zio-rocksdb`s tests are written: https://github.com/zio/zio-rocksdb/

**Comment by Shastick** [comment]
Will give this one a shot to get setup with the zio-flow codebase.😘

**Comment by vigoo** [comment]
I'll merge RC6 update very soon, make sure you pull it :)
