### ISSUE TITLE
Create an initial version of zio-flow's REST API 

### ISSUE THREAD

**Issue by vigoo** [zio/zio-flow#183]
**ISSUE**

We want to have a `zio-flow` server with a REST API which allows clients to submit workflows for execution, and provide other features to manipulate/observe these workflows.

This issue is the first step in this (https://github.com/zio/zio-flow/issues/177). 

**SOLUTION**

- Create `zio-http` server in the main `zio-flow` project (later we will split it up to definition and execution sub projects (https://github.com/zio/zio-flow/issues/176)). 
- Make sure that for the whole lifecycle of the HTTP server, a single `PersistentExecutor` instance is created
- On startup it should call the executor's `restartAll` method to make sure all persisted running workflows get restarted
- Create an endpoint for submitting workflows for immediate execution. The payload of this request should be a serialized `ZFlow` (using zio-schema with JSON codec) and it should be passed to the executor's `submit` with a generated unique identifier which is returned to the user
- Create another endpoint to poll for the result of a running workflow. This should be done by the identifier generated for it on creation. The result is an arbitrary `zio-schema` DynamicValue that can be serialized to JSON. This step will require some changes in the `Executor` interface itself.

**IMPACT**

This is a very important step in making zio-flow usable for real problems. Once we have a running zio-flow service we can submit workflows to, we can start building a more advanced API for it that supports storing parameteric workflows, observing running state and variables, etc.

**WHERE TO LOOK**

 - https://github.com/dream11/zio-http
 - https://github.com/zio/zio-flow/blob/main/zio-flow/shared/src/main/scala/zio/flow/internal/ZFlowExecutor.scala

**PROBLEMATIC ISSUES**

You will see that the executor interface does not support polling for result currently. It is however treats the flow identifier as a unique identifier of workflows and if one with the same ID is already running, resubmitting it will just wait for the existing workflow's result. This means that everything is prepared to have a different interface more suitable for the HTTP API which is a combination of a "start and forget" and a "poll for result" methods.

Also `submit` requires a result and error schema for converting back the dynamic values to typed ones. We should probably have variants for the HTTP API that does not do that, and returns the `DynamicValue`s directly.

**Comment by Shastick** [comment]
Will start to look into this one (Can't auto-assign, it seems, or did I miss something?)

**Comment by vigoo** [comment]
An initial version of this has been merged
