### ISSUE TITLE
"Failed to cast" error with Remote.Cons

### ISSUE THREAD

**Issue by TomasMikula** [zio/zio-flow#191]
The following test case (when added to `PersistentExecutorSpec`)

```scala
    testFlow("cons") {
      ZFlow(Remote(1))
        .map(Remote.Cons(Remote(Nil), _))
    } { result =>
      assertTrue(result == List(1))
    },
```

results in

> Exception in thread "zio-fiber-28" zio.FiberFailure: Failed to evaluate remote: Failed to cast Primitive((),unit) to schema Sequence(Primitive(int,Chunk()), List)

**Comment by vigoo** [comment]
If you explicitly give the type of `Nil` it works:
```scala
testFlow("cons") {
      ZFlow(Remote(1))
        .map(Remote.Cons(Remote[List[Int]](Nil), _))
    } { result =>
      assertTrue(result == List(1))
    },
```

without that the 
```  implicit val nil: Schema[Nil.type] = singleton(Nil)```
is picked up from zio-schema instead of a sequence of int schema.

I think this is a zio-schema issue similar to another I already fixed in it regarding `Left` and `Right` was not encoded the same way as an `Either`.
