### ISSUE TITLE
"Failed to cast" error with foreach and foreachPar

### ISSUE THREAD

**Issue by TomasMikula** [zio/zio-flow#192]
Both following tests (when added to `PersistentExecutorSpec`)

```scala
    testFlow("foreach") {
      ZFlow.foreach(Remote(List.range(1, 10)))(ZFlow(_))
    } { res =>
      assertTrue(res == List.range(1, 10))
    },

    testFlow("foreachPar") {
      ZFlow.foreachPar(Remote(List.range(1, 10)))(ZFlow(_))
    } { res =>
      assertTrue(res == List.range(1, 10))
    },
```

result in

> Exception in thread "zio-fiber-84" zio.FiberFailure: Failed to evaluate remote: Failed to cast NoneValue to schema EnumN(Case(Value,Transform(CaseClass3(Field(valueType,Primitive(string,Chunk())),Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(optional,Primitive(boolean,Chunk()))), SourceLocation(/home/runner/work/zio-schema/zio-schema/zio-schema/shared/src/main/scala/zio/schema/ast/SchemaAst.scala,194,25)),Chunk()) :+: Case(Sum,CaseClass3(Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(cases,Sequence(Tuple(Primitive(string,Chunk()),$Lazy$,Chunk()), Chunk)),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Case(Either,CaseClass4(Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(left,$Lazy$),Field(right,$Lazy$),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Case(Product,CaseClass3(Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(fields,Sequence(Tuple(Primitive(string,Chunk()),$Lazy$,Chunk()), Chunk)),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Case(Tuple,CaseClass4(Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(left,$Lazy$),Field(right,$Lazy$),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Case(Ref,CaseClass3(Field(refPath,Sequence(Primitive(string,Chunk()), Chunk)),Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Case(ListNode,CaseClass3(Field(item,$Lazy$),Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Case(Dictionary,CaseClass4(Field(keys,$Lazy$),Field(values,$Lazy$),Field(path,Sequence(Primitive(string,Chunk()), Chunk)),Field(optional,Primitive(boolean,Chunk()))),Chunk()) :+: Empty,Chunk())

**Comment by vigoo** [comment]
These tests are now passing
