### ISSUE TITLE
Add ExprList

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-flow#20]
`ExprList` will be a trait that adds methods to anything of the form `Expr[List[A0]]`. The trait should be defined in an `ExprList.scala` file, and mixed into the `Expr[A]` trait that is inside `Expr.scala`.

There are two fundamental operations needed:

 - A way to deconstruct a list into `Option[(A0, List[A0])]` (`Uncons`)
 - A way to construct a list from `(A0, List[A0]])` (`Cons`)

Given construction and deconstruction operations, it should be possible to further expand the operations to provide many of the method's on Scala's own `List` type. Now, these methods will have different signatures in some cases. For example, `map` will not have signature `def map(f: A => B): Expr[List[B]]`, but rather, `def map(f: Expr[A] => Expr[B]): Expr[List[B]]`. Similarly, `take` will not have signature `def take(n: Int): List[A]`, but rather, `def take(n: Expr[Int]): Expr[List[A]]`. So slight modification of the method signatures will be necessary. However, they should have the same semantics as the List methods.

Useful list methods to add:

 - `map`
 - `take`
 - `takeWhile`
 - `drop`
 - `dropWhile`
 - `flatMap`
 - `filter`
 - `zip`
 - `foldLeft`
 - `reverse`
 - `foldRight`
 - etc.

**Comment by ashprakasan** [comment]
Done - https://github.com/zio/zio-flow/commit/70af565cc27d21245a66809fb69fe07f7004ee44
