### ISSUE TITLE
Make onError and onSuccess optional in `ZFlow#Fold`

### ISSUE THREAD

**Issue by vigoo** [zio/zio-flow#202]
As a serialization optimization - as `flatMap`/`map` is the most common case with a default "identity" error case

**Comment by tonymorris** [comment]
I'm on this one

**Comment by tonymorris** [comment]
I nearly have this one complete. However, I am stuck on the following:

@vigoo 

> in case they are None return with an identity remote function

However, there is no way to create an identity value of type `EvaluatedRemoteFunction[A, ZFlow[R, E2, B]]`.

I put it down to one of the following:

* I don't need a value of this type, in which case, I am not sure what we might mean.
* There is some way to create a value of this type.

Any comments most welcome.

**Comment by vigoo** [comment]
Yeah identity was not the proper word, what I meant is that when you deserialize the `(Flow, Option[EvaluatedRemoteFunction], Option[EvaluatedRemoteFunction], Schema, Schema)` product, you would get rid of the `Option`s in the `construct` function by something like

- onError.getOrElse("e => ZFlow.fail(e)")
- onSuccess.getOrElse("a => ZFlow.succeed(a)")

how can we create these `EvaluatedRemoteFunction`s? We don't have a particular `E` and `A` in the deserializer but we have the error and result schema (as they are serialized too). `EvaluatedRemoteFunction` is just a pair of a `Remote.Variable` and an arbitrary `Remote` that somewhere refers to the given variable. So what we need is something like `EvaluatedRemoteFunction(Remote.Variable(randomId, errorSchema), Remote.Flow(ZFlow.Fail(Remote.Variable(randomId)))`. I am not 100% sure you can generate this with the implicit conversions (as there are no scala-level type info present) but you can definitely create it "by hand" like this. 

Note that on my branch I'm changing this a bit (separating the concept of a "local" variable used for function evaluation vs the user-defined remote variables) but that would not change much - and I think this PR will be ready first :)

**Comment by tonymorris** [comment]
Ah OK understood, thanks!
