### ISSUE TITLE
Legal constructs lead to unbound variable during execution

### ISSUE THREAD

**Issue by TomasMikula** [zio/zio-flow#219]
The trivial program below, constructed via legal operations,

```scala
    testFlow("unbound function input") {
      // 😱 EvaluatedRemoteFunction[A, B] is also a Remote[B]
      val ri: Remote[Int] =
        Remote.EvaluatedRemoteFunction.make[Int, Int](i => i)

      ZFlow(ri)
    } { i =>
      assertTrue(i != 0)
    }
```

leads to an exception when _executed:_

```
java.io.IOException: Failed to evaluate remote: Cannot evaluate binding 09be16c7-f754-4a4b-a2e9-96a9d485731a, it has to be substituted
```

There are 2 problems:
 1. That an illegal program is so easily constructed using _legal_ operations. 
     (It's not like I'm leaking a variable out of its scope through a mutable var or something.)

     The problem here is that `EvaluatedRemoteFunction[A, B]` extends `Remote[B]`. 
     Possible solutions:
      - Can it not extend `Remote` at all?
      - Can it extend something like `Remote[Fun[A, B]]`?
 2. That such malformed programs are not detected **before** execution.

**Comment by vigoo** [comment]
Good point, thanks again!
I feel like the better solution would be that it's a `Remote[Fun[A, B]]`, will explore that.
