### ISSUE TITLE
Introduce ZIO Schema as a dependency and refactor the code to use Schema

### ISSUE THREAD

**Issue by jdegoes** [zio/zio-flow#4]

**Comment by ashprakasan** [comment]
The latest release of [zio-schema](https://search.maven.org/artifact/dev.zio/zio-schema_2.12/0.0.5/jar) (v0.0.5) does not support some constructs we need in zio-flow. 
AFAIK, there are no snapshot releases. So maybe we need to do something like this - https://alvinalexander.com/scala/using-github-projects-scala-library-dependencies-sbt-sbteclipse/
