### ISSUE TITLE
trigonometric law violation in RemoteFractional

### ISSUE THREAD

**Issue by phderome** [zio/zio-flow#55]
Given the identity `sin^2(theta) + cos^2(theta) = 1` we have that
`cos(theta) = square_root(1 - sin^2(theta))` however the root is missing in 

```  final def cos[A1 >: A](implicit fractional: Fractional[A1]): Remote[A1] = {
    implicit val schemaA1: Schema[A1] = fractional.schema
    Remote(fractional.fromDouble(1.0)) - sin(fractional) pow Remote(fractional.fromDouble(2.0))
  }
```

Additionally I'd recommend declaring a set of constants  in terms of PI such HALF_PI, 2PI, MINUS_PI with whichever naming convention makes sense for the project so that the literal below is expressed in terms of HALF_PI instead of using a magic number:

```
fractional.fromDouble(1.571)
```

**Comment by ashprakasan** [comment]
Ah thats a bug. Thanks @phderome. I will add constants for PI, HALF_PI etc too.

**Comment by phderome** [comment]
In fact I'd question any trigonometric computation in this library, why not delegate it all to standard library/runtime?

**Comment by adamgfraser** [comment]
I'm not sure we should even by specifying numeric operations of this complexity. I don't believe some of these operators are even defined in `java.math`. I would think our initial design goal should be to just replicate the functionality provided by the Java / Scala standard libraries in the `Remote` world. This would mean limiting ourselves to operators defined by those libraries.

I would also think we should limit our support for operators like `sin` to `Double` versus generalized numeric data types. This would again be consistent with the support provided by the language and would allow us to just delegate to existing operators in our implementation versus doing new implementations ourselves.

Then other libraries could potentially provide support for other remote numeric data types or we could add those in the future but doesn't seem like this is a priority relative to other challenges we want to solve in this space.
