### ISSUE TITLE
Make `schemas` for `Remote` and `ZFlow`

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-flow#69]
Every `Zflow` needs to be serializable. 

Why?
During the evaluation (by the interpreter) of a ZFlow, an `instruction stack` is created and stored as a part of the `State` of execution. The `instruction stack` is similar to a JVM runtime stack and contains all instructions that need to be carried out. After each step in the interpretation process,  `State` needs to be written to a durable storage (to support restarting in case of failure). The instruction stack is a `List[ZFlow]`.This is why schema of ZFlow is required.

**Comment by vigoo** [comment]
Done in #138
