### ISSUE TITLE
Create extension methods on Remote[Either]

### ISSUE THREAD

**Issue by ashprakasan** [zio/zio-flow#79]

**Comment by michivi** [comment]
I would like to work on this one :)

**Comment by michivi** [comment]
The #83 PR adds the `swap`, `toOption` and `getOrElse` extension methods to `Remote[Either]`.

There's no `toTry` implementation yet, as I had some questions. I'm assuming that the result is a `Remote[Try[B]]` and not `Try[B]`. If I'm not mistaken, it means that we need an instance for `Schema[Throwable]`, or at least an instance of `Schema[A]` with `A` being a subclass of `Throwable`, and a schema for `Try`. There's no such instance instances for now in ZIO Schema. Would that even be possible? Would that make sense FP-wise? With a `Try`, wouldn't we lose information on the failure, losing the benefits of FP?

**Comment by adamgfraser** [comment]
Closed by #83.
